version: 0.0.{build}
os: Visual Studio 2015
install:
- dnvm upgrade -r clr
- dnu restore
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: dnx -p src\CommandRouting.UnitTests\project.json test